# Generated by Django 4.0 on 2022-01-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_course_analyzeese_alter_course_analyzet1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='class_code',
            new_name='course_code',
        ),
    ]
