# Generated by Django 4.0 on 2022-01-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_course_analyzeese_alter_course_analyzet1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseoutcomeverb1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='courseoutcomeverb2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='courseoutcomeverb3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='courseoutcomeverb4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='courseoutcomeverb5',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
