# Generated by Django 4.0 on 2022-01-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_faculty',
            field=models.BooleanField(default=False, verbose_name='Is faculty'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_hod',
            field=models.BooleanField(default=False, verbose_name='Is hod'),
        ),
    ]
