# Generated by Django 4.0 on 2022-01-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
    ]
