# Generated by Django 4.0 on 2022-06-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_course_finalsubmit_alter_course_analyzeese_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='finalsubmit',
            field=models.CharField(default=False, max_length=10, null=True),
        ),
    ]
