# Generated by Django 4.0 on 2022-06-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_alter_course_finalsubmit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='finalsubmit',
            field=models.BooleanField(default=False),
        ),
    ]
